version: 1.1.0
name: launcher_shortcuts
homepage: https://github.com/camilo1498/app_shortcuts
description: "A comprehensive Flutter plugin for managing dynamic app shortcuts on both iOS and Android platforms. "


environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.5.0
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pco.camilo.launcher_shortcuts
        pluginClass: LauncherShortcutsPlugin
      ios:
        pluginClass: LauncherShortcutsPlugin
